apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config-python-search
  namespace: {{.Values.deployment.application_name}}
data:
  agent.cfg: |-
    [agent]
    app = healthcare
    tier = searchService
    node = searchService
    [controller]
    host = XYZ.saas.appdynamics.com
    port = 80
    ssl = off
    account = ACCOUNT_NAME
    accesskey = ACCESS_KEY