apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.application_name}}
  namespace: {{.Values.deployment.application_name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.deployment.application_name}}
  template:
    metadata:
      labels:
        app: {{.Values.deployment.application_name}}
        version: {{.Values.deployment.image_tag}}
    spec:
      securityContext:
      #  allowPrivilegeEscalation: false
      #  runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: {{.Values.deployment.application_name}}
          image: {{.Values.deployment.image}}:{{.Values.deployment.image_tag}}
          securityContext:
              capabilities:
                  add: ["NET_ADMIN","NET_RAW"]
          env:
            - name: CALENDAR_SERVICE
              value: "healthcare-calendar.healthcare-calendar.svc.cluster.local"
            - name: CALENDAR_PORT
              value: "5050"
            - name: REDIS_SERVICE
              value: "emear-pvt-rm-health.redis.cache.windows.net"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_ACCESS_KEY
              value: {{.Values.deployment.redis_access_key}}
            - name: PREDICTOR_SERVICE
              value: "healthcare-predictor.healthcare-predictor.svc.cluster.local"
            - name: PREDICTOR_PORT
              value: "5001"
            - name: REFUND_SERVICE
              value: "healthcare-refund.healthcare-refund.svc.cluster.local"
            - name: REFUND_PORT
              value: "5050"
            - name: OFFER_SERVICE
              value: "healthcare-offers.healthcare-offers.svc.cluster.local"
            - name: SEARCH_SERVICE
              value: "healthcare-search.healthcare-search.svc.cluster.local"
            - name: SEARCH_PORT
              value: "5051"
            - name: HTTP_PROXY
              value: 'http://proxy-wsa.esl.cisco.com:80/'
            - name: HTTPS_PROXY
              value: 'http://proxy-wsa.esl.cisco.com:80/'
            - name: NO_PROXY
              value: 'calendar,frontend,predictor,redis,refund,search,localhost,127.0.0.1,10.96.0.1'
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-data
              mountPath: /tmp/appd/run
            - name: agent-config
              mountPath: /opt/appdynamics/agent.cfg
              subPath: agent.cfg
          ports:
          - containerPort: 5051
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5051
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5051
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: agent-config
          configMap:
            name: agent-config-python-search
          
    
    
    