apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.deployment.application_name}}
    version: "1"
  name: {{.Values.deployment.application_name}}
  namespace: {{.Values.deployment.application_name}}
spec:
  ports:
  - name: http 
    port: 5051
    protocol: TCP
    targetPort: 5051
  selector:
    app: {{.Values.deployment.application_name}}
    version: "1"
  type: LoadBalancer